server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  datasource:
    name: db
    type: com.alibaba.druid.pool.DruidDataSource #表明使用Druid连接池
    username: root
    #    password: zmy1022a.
    password: 123456
    #    url: jdbc:mysql://127.0.0.1:3306/houtaisql?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://47.94.8.32:3306/wfw?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 500
    maxActive: 1000 #最大连接池数量
    initialSize: 10 #初始化时建立物理连接的个数
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
#      defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.xinchen.springcloud.entities